#pragma once
#include "regionizedText.h"
class common {
    MHPP("begin common") // === autogenerated code. Do not edit ===
    public:
    	static std::string errmsg(const regionizedText& body, csit_t iBegin, csit_t iEnd, const string& filename, const string& msg);
    MHPP("end common")
};