#pragma once
#include <regex>
#include <string>
#include <vector>

#include "regionized.h"
using std::vector, std::string;  // prj convention
// baseclass for a parsed("MHPP xyz") keyword
class MHPP_keyword {
    MHPP("begin MHPP_keyword")  // === autogenerated code. Do not edit ===
   public:
    static vector<MHPP_keyword> parse(const regionizedText& t, const string& filenameForError);
    MHPP("end MHPP_keyword")
   private:
    static const std::regex rMHPP;
};